compile:
	ocamlbuild -I lib/src nqueens.byte
	ocamlbuild -I lib/src magicSquare.byte
	ocamlbuild -I lib/src sudoku.byte
	ocamlbuild -I lib/src sendMoreMoney.byte
	ocamlbuild -I lib/src cycle.byte
	ocamlbuild -I lib/src sevenEleven.byte
	ocamlbuild -I lib/src golomb.byte
	ocamlbuild -I lib/src coloring.byte

clean:
	ocamlbuild -clean
